#!/bin/bash

#Script for programming Papilio One 250K/500K boards

PROG=papilio-prog
BSCAN=~/etc/bscan/bscan_spi_lx9_qfp144.bit
echo $BSCAN

if [ ! -e $BSCAN ] ; then \
	echo "Error! Could not find $BSCAN!"
	exit -1	
fi

$PROG -v -f $1.bit -b $BSCAN -sa -r
$PROG -c
